pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Install dependencies and build your application
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                // Run your tests
                sh 'npm run test'
            }
        }

        stage('Deploy to Vercel') {
            steps {
                script {
                    // Install Vercel CLI
                    sh 'npm install -g vercel'

                    // Authenticate with Vercel using your token
                    sh 'vercel login --token P6aIcDSQPcKeLR4UO7Q29Wqs'

                    // Deploy to Vercel
                    sh 'vercel --prod'
                }
            }
        }
    }
}
