pipeline {
    agent any
	environment {
	      VERCEL_TOKEN = credentials('yUum3VoqZQc2489GYwjDl1oD')
	}
    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Build your application
                sh 'mvn clean install'
            }
        }
        
        stage('Test') {
            steps {
                // Run your tests
                sh 'mvn test'
            }
        }
    }
}
