pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                deleteDir() // Clean workspace
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('DevOps') {
                    // Build your application
                    sh 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('DevOps') {
                    // Run your tests
                    sh 'mvn test'
                }
            }
        }
    }
}
