pipeline {
    agent any

    environment {
        VERCEL_TOKEN = credentials('P6aIcDSQPcKeLR4UO7Q29Wqs')
    }

    stages {
        stage('Build') {
            steps {
                // Install dependencies and build your application
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                // Run your tests
                sh 'npm run test'
            }
        }

        stage('Deploy to Vercel') {
            steps {
                script {
                    // Set Vercel token as an environment variable
                    withCredentials([string(credentialsId: 'P6aIcDSQPcKeLR4UO7Q29Wqs', variable: 'VERCEL_TOKEN')]) {
                        // Deploy to Vercel
                        sh 'vercel --prod'
                    }
                }
            }
        }
    }
}
